import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import ts from 'typescript';
function fixture(){const state={},jobs=new Map(),calls=[];const responses=[];
 const db=()=>({prepare(q){return {bind(...v){this.values=v;return this;},async first(){return {n:0};},async run(){jobs.set(this.values[0],this.values);}};},async batch(rows){for(const r of rows)await r.run();}});
 const modules={'./store':{db,setting:async(k,v)=>{state[k]=v;}},'./indexer':{rpc:async(method,params)=>{calls.push(params[0]);return responses.shift();}}};
 const out=ts.transpileModule(fs.readFileSync(new URL('../lib/transfer-history.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};new Function('require','exports',out)(n=>modules[n],exports);
 const p={id:'test',wallet:'0x'+'a'.repeat(40)},c=()=>({rpcUrl:'https://monad-mainnet.g.alchemy.com/v2/test',...state});return {state,jobs,calls,responses,run:h=>exports.discoverTransfers(p,h,c())};}
const tx='0x'+'b'.repeat(64);const transfer={hash:tx,blockNum:'0x5'};
test('history fixes its head across pages, deduplicates discoveries and then scans new blocks',async()=>{const f=fixture();f.responses.push({transfers:[transfer],pageKey:'page2'},{transfers:[transfer]});await f.run(10);assert.equal(f.jobs.size,1);assert.equal(f.state['alchemyDiscovery:test:initialized'],undefined);f.responses.push({transfers:[]});await f.run(15);assert.equal(f.calls[2].toBlock,'0xa');assert.equal(f.calls[2].pageKey,'page2');assert.equal(f.state['alchemyDiscovery:test:recentNext'],'11');f.responses.push({transfers:[]},{transfers:[]});await f.run(20);assert.equal(f.calls[3].fromBlock,'0xb');assert.equal(f.state['alchemyDiscovery:test:recentNext'],'21');});
test('malformed provider data never advances discovery or queues guessed transactions',async()=>{const f=fixture();f.responses.push({transfers:[{hash:'bad',blockNum:'0x5'}]});await assert.rejects(f.run(10),/Invalid transfer history/);assert.equal(f.jobs.size,0);assert.equal(f.state['alchemyDiscovery:test:history:fromAddress'],undefined);});
