import {db,config,failure} from '../lib/store';import {performance,periodStart,type Trade} from '../lib/accounting';
export async function GET(r:Request){try{const period=new URL(r.url).searchParams.get('period')||'week';const since=periodStart(period);const c=await config();const p=await db().prepare('SELECT * FROM profiles WHERE active=1 ORDER BY name').all<any>();const traders=[];let allTrades:any[]=[];const buysSince=Math.floor(Date.now()/1000)-7*86400;const recentBuys=await db().prepare("SELECT t.*,p.name,p.handle,p.avatar,p.id as profileId FROM trades t JOIN profiles p ON p.wallet=t.wallet WHERE p.active=1 AND t.side='BUY' AND t.time>=? ORDER BY t.time DESC LIMIT 500").bind(buysSince).all<any>();
 for(const profile of p.results){const rows=await db().prepare('SELECT * FROM trades WHERE wallet=? ORDER BY block,time,id LIMIT 20001').bind(profile.wallet).all<Trade>();const transfers=await db().prepare('SELECT * FROM transfers WHERE wallet=? ORDER BY block LIMIT 50001').bind(profile.wallet).all<any>();const pending=await db().prepare("SELECT COUNT(*) as n FROM chain_jobs WHERE wallet=? AND status='pending'").bind(profile.wallet).first<any>();const unresolved=await db().prepare("SELECT COUNT(*) as n FROM chain_jobs WHERE wallet=? AND status IN ('pending','review')").bind(profile.wallet).first<any>();const target=Number(c.liveObservedHead)||0;const fresh=Number(c.liveHeadCheckedAt)>Date.now()/1000-90;const complete=fresh&&target>0&&c['historyNext:'+profile.id]==='-1'&&Number(c['tipCursor:'+profile.id])>target&&unresolved.n===0&&!c.liveError&&rows.results.length<=20000&&transfers.results.length<=50000;

 const stats=performance(rows.results,transfers.results,since);const selected=rows.results.filter(t=>t.time>=since);const buyCount=selected.filter(t=>t.side==='BUY').length;const sellCount=selected.filter(t=>t.side==='SELL').length;traders.push({...profile,live:{start:Number(c["tipStart:"+profile.id])||null,cursor:Number(c["tipCursor:"+profile.id])||null,head:Number(c["liveHead:"+profile.id])||null,historyNext:c["historyNext:"+profile.id]===undefined?null:Number(c["historyNext:"+profile.id])},...stats,buyCount,sellCount,importedTrades:rows.results.length,complete,pending:pending.n,historyCapped:rows.results.length>20000||transfers.results.length>50000});allTrades.push(...rows.results.filter(t=>t.time>=since).map(t=>({...t,sale:stats.saleResults[t.id]||null,provisional:!complete,name:profile.name,handle:profile.handle,avatar:profile.avatar,profileId:profile.id})));}
 const tokens=await db().prepare('SELECT * FROM tokens WHERE valid=1').all<any>();const activity=tokens.results.map(t=>{const trades=allTrades.filter(s=>s.token===t.address);return {...t,buyers:new Set(trades.filter(s=>s.side==='BUY').map(s=>s.wallet)).size,sellers:new Set(trades.filter(s=>s.side==='SELL').map(s=>s.wallet)).size,trades:trades.length};}).filter(t=>t.trades>0).sort((a,b)=>b.trades-a.trades);
 const jobs=await db().prepare("SELECT status,COUNT(*) as count FROM chain_jobs GROUP BY status").all<any>();
 allTrades.sort((a,b)=>b.time-a.time);return Response.json({live:{observedHead:Number(c.liveObservedHead)||null,headCheckedAt:Number(c.liveHeadCheckedAt)||null,retryAt:Number(c.rpcRetryAt)||null,lastRun:Number(c.liveLastRun)||null,error:c.liveError||"",jobs:jobs.results},recentBuys:recentBuys.results,buysSince,traders,trades:allTrades.slice(0,150),sells:allTrades.filter(t=>t.side==='SELL').slice(0,150),buys:allTrades.filter(t=>t.side==='BUY').slice(0,150),tokens:tokens.results.map(t=>({...t,decimals:c['chainToken:'+t.address]?JSON.parse(c['chainToken:'+t.address]).decimals:18})),activity,period,since,lastSync:Number(c.lastSync)||null,syncError:c.liveError||'',indexing:{effectiveBlockRange:Math.min(Number(c.chunk||100),Number(c.rpcMaxLogRange)||5000000),rateLimitedUntil:Math.floor(Number(c.rpcRetryAt||0)/1000)},methodology:'MON-denominated realised trading P&L uses weighted-average cost and receipt-derived swap amounts, less transaction gas. Onchain-pool-quote amounts are pool estimates before external routing fees. Legacy receipt-checked imports are retained. Non-MON quote tokens and unsupported routes are excluded from MON P&L. Transferred inventory is excluded until the position resets to zero. Win rate counts fully closed position cycles. Rankings cover tracked wallets only; incomplete histories are unranked. Provisional results use imported trades only and can change as missing buys, sells and transfers are discovered. Sales without a matched imported cost basis and ambiguous same-block transaction ordering are excluded; no win rate is shown without an eligible closed cycle.'},{headers:{'Cache-Control':'no-store'}});
 }catch(e){return failure(e);}}
